### ISSUE TITLE
How to turn on/off display and adjust contrast, etc.?

### ISSUE THREAD

**Issue by DarumasLegs** [adafruit/Raspberry-Pi-Installer-Scripts#122]
I have the 1.3" 240x240 MiniPiTFT display on my RPi 3B+, and I'd like to use one of the buttons on the display as a toggle switch to turn on and off the display (this is for a video camera that will be running for hours at a time - I only need the display to be on when I'm aiming the camera - I want to turn it off to maximize battery life). How can I do this?

The second question is that I noticed that the brightness of the MiniPiTFT display is significantly brighter than what is shown on an attached HDMI display. I worry that if I adjust the aperture of the lens (I'm using the HQ Camera Module) based on what I see on the MiniPiTFT, it will be way too dark. Is the brightness adjustable at all - if so, how?

**Comment by makermelissa** [comment]
Hi, there are a couple of ways to adjust the brightness of a display. The first way it to use PWM to turn the backlight on and off at a certain rate. I just took a look at the schematic at https://learn.adafruit.com/adafruit-mini-pitft-135x240-color-tft-add-on-for-raspberry-pi/downloads. It appears the backlight is on GPIO22.

The second way is by sending a brightness command. The ST7789 data sheet is on the same page as the schematic and has more information.

Unfortunately since the display is controlled through the Raspberry Pi, sending a brightness command is probably not feasible. However, you might still be able to toggle the PWM pin using the Blinka library. You can find more information here: https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/pwm-outputs-servos.

Hopefully that helps. For more questions like this, I would suggest posting in the forums at forums.adafruit.com. Since this isn't an actual issue with this repo, I'm closing it.
