### ISSUE TITLE
Control backlight brightness

### ISSUE THREAD

**Issue by occasional-contributor** [adafruit/Raspberry-Pi-Installer-Scripts#292]
I am using an [2" ST7789 TFT](https://www.adafruit.com/product/4311) using [adafruit-pitft-mipi.py](https://github.com/adafruit/Raspberry-Pi-Installer-Scripts/blob/main/adafruit-pitft-mipi.py#L161-L177). How is backlight brightness controlled?

**Comment by makermelissa** [comment]
Hi, sorry for the delay. I just found the answer, sort of. If you take a look at https://github.com/raspberrypi/linux/blob/rpi-6.1.y/arch/arm/boot/dts/overlays/mipi-dbi-spi-overlay.dts you can see all of the overrides available. It looks like these are the options pertaining to the brightness:
```
		backlight-gpio        = <0>, "+10+11",
					<&backlight_gpio>, "gpios:4";
		backlight-pwm         = <0>, "+20+21+22+23+24";
		backlight-pwm-chan    = <&backlight_pwm>, "pwms:4";
		backlight-pwm-gpio    = <&pwm_pins>, "brcm,pins:0";
		backlight-pwm-func    = <&pwm_pins>, "brcm,function:0";
		backlight-def-brightness = <&backlight_pwm>, "default-brightness-level:0";
```
You will likely need to connect the lite pin up to a GPIO (maybe something like GPIO 18, which has PWM). Then set the backlight-gpio in /boot/firmware/config.txt (or /boot/config.txt if the firmware folder doesn't exist). After that, I'm not sure because I have never set the brightness to something other than full through a driver.
